---
# Master Playbook für Nomad Cluster Setup
# Clients werden via Cloud-Init konfiguriert
- name: Common Setup für alle Nodes
  import_playbook: common.yml
  when: "'nomad_servers' in groups"

- name: Consul Server Setup
  import_playbook: consul.yml
  when: "'nomad_servers' in groups"

- name: Nomad Server Setup
  import_playbook: nomad-server.yml
  when: "'nomad_servers' in groups"
